# We pretend to be Java because we need GNU Octave which is not 
# available (as of January 2016)
language: java

dist: xenial

addons:
  apt:
    sources:
      - sourceline: 'ppa:alexlarsson/flatpak'
    packages:
      - flatpak
      
###############################################################################
cache:
  # Downloading octave takes a while, so let's cache apt
  apt: true
  directories:
    # Cache octave packages
    - $HOME/octave
    # Cache other packages
    - $HOME/external_cache

###############################################################################
# Command to install dependencies
before_install:
  - git submodule update --init
  - sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - sudo flatpak install flathub org.octave.Octave

###############################################################################
install:
  ADDPATH_COMMAND="replab_addpaths(2,1);"
  INSTALL_SDPT3="cd external/SDPT3; install_sdpt3; cd ../..;"

###############################################################################
before_script:
  - TEST_COMMAND="exit(~replab_runtests(1));";
    echo "TEST_COMMAND| $TEST_COMMAND";
  # Double-check we are still in the right directory
  - pwd
  # Check what octave packages we have installed
  - flatpak run org.octave.Octave -q --eval "ver"
  # ---------------------------------------------------------------------------
  # Remove any cached results files from previous build, if present
  - rm -f testresults.xml;
  # ---------------------------------------------------------------------------

###############################################################################
script:
  - flatpak run org.octave.Octave -q --eval "$ADDPATH_COMMAND $INSTALL_SDPT3 $TEST_COMMAND";

###############################################################################
after_script:
  # Check where we ended up and what's going on where we are
  - pwd
  - ls -alh
  - bash <(curl -s https://codecov.io/bash)

